### ISSUE TITLE
Make TextAssets a part of Built Resources

### ISSUE THREAD

**Issue by SybelBlue** [SybelBlue/trombone-input#36]

**Comment by bretjackson** [comment]
The trials seem to be loading in the cave but I'm getting an error in Main.RunNextTrail where it says it is "skipped running trial because outputDisplay is null". Could be related to this issue.

If it helps you can run your build on the command line with the option "-logFile pathToFile.txt" and get the debug output.

**Comment by SybelBlue** [comment]
The Main script had Trial Execution Mode set to OnlyInEditor, so the bug is fixed. Before I found this, I also created the StreamedAssets folder to allow the trials to remain as files on the OS filesystem and have direct reference to them. Hopefully this will prevent any potential build issues
