### ISSUE TITLE
For perfect trials, make correctly typed spaces underline in green

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#40]
Right now it's hard to tell if a space was typed correctly of if the stylus just didn't give any output.

**Comment by SybelBlue** [comment]
I tried underlining the spaces but the rich text parser for TMP ignored the underlines, so I made them dashes so that it will continue to leave word breaks for text wrapping in the text box. I can make them underscores or underline the entire phrase, but the parser will ignore trailing spaces and parses bullets as a non-whitespace character
