### ISSUE TITLE
make pizza text wheel bigger and centered under the output canvas

### ISSUE THREAD

**Issue by bretjackson** [SybelBlue/trombone-input#43]
Right now it's really hard to read the letters since they are so small and off to the side

**Comment by zspilka** [comment]
Pizza text wheel is bigger and centered under output canvas. In addition, I have made it so that the End Practice Button, live drop down menu, and Challenge Type Indicator shift either to the left or the right to accomodate for the input text interface. Their--the End Practice Button, Live Drop Down Menu, and the Challenge Type Indicator's--shift only occurs in this text input interface; in all other text input interfaces, the End Practice Button, Live Drop Down Menu, and the Challenge Type Indicator remain and/or return to their original position on the screen.
